# Generated by Django 3.2.3 on 2021-05-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LatestNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short_text', models.TextField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('date', models.CharField(max_length=12)),
                ('image', models.TextField(max_length=2048)),
                ('writer', models.CharField(max_length=50)),
            ],
        ),
    ]
