# Generated by Django 3.2.3 on 2021-05-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('newsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsappmodel',
            name='about',
            field=models.TextField(default='-', max_length=255),
        ),
    ]
