# Generated by Django 3.2.3 on 2021-05-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('newsApp', '0002_newsappmodel_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsappmodel',
            name='fb',
            field=models.TextField(default='http://fb.com/', max_length=255),
        ),
        migrations.AddField(
            model_name='newsappmodel',
            name='twitter',
            field=models.TextField(default='http://twitter.com/', max_length=255),
        ),
        migrations.AddField(
            model_name='newsappmodel',
            name='youtube',
            field=models.TextField(default='http://youtube.com/', max_length=255),
        ),
    ]
