# Generated by Django 3.2.3 on 2021-05-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('newsApp', '0004_auto_20210515_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsappmodel',
            name='contactNumber',
            field=models.CharField(default='+91', max_length=13),
        ),
    ]
